#ifndef _VIRTIO_BLK_REGISTERS_H_
#define _VIRTIO_BLK_REGISTERS_H_ 1



// Features
#define VIRTIO_BLK_F_SIZE_MAX 1
#define VIRTIO_BLK_F_SEG_MAX 2
#define VIRTIO_BLK_F_BLK_SIZE 6

// Registers
#define VIRTIO_BLK_REG_CAPACITY 0x00
#define VIRTIO_BLK_REG_BLK_SIZE 0x14



#endif
