#ifndef _KERNEL_CONFIG_H_
#define _KERNEL_CONFIG_H_ 1



#define CONFIG_DISABLE_USER_AML 0
#define CONFIG_DISABLE_USER_BIOS_DATA 0
#define CONFIG_DISABLE_USER_MAC_ADDRESS 0
#define CONFIG_DISABLE_USER_MEMORY_COUNTERS 0
#define CONFIG_DISABLE_USER_MEMORY_RANGES 0
#define CONFIG_DISABLE_USER_NUMA 0



#endif
