#ifndef _KERNEL_CONFIG_H_
#define _KERNEL_CONFIG_H_ 1
#include <kernel/types.h>



#define CONFIG_DISABLE_USER_AML 1
#define CONFIG_DISABLE_USER_BIOS_DATA 1
#define CONFIG_DISABLE_USER_MAC_ADDRESS 1
#define CONFIG_DISABLE_USER_MEMORY_COUNTERS 1
#define CONFIG_DISABLE_USER_MEMORY_RANGES 1
#define CONFIG_DISABLE_USER_NUMA 1



#endif
