#include <glsl/builtin_types.h>
#include <sys/types.h>



static const char*const _glsl_builtin_type_to_string[GLSL_BUILTIN_MAX_TYPE+1]={
	[GLSL_BUILTIN_TYPE_NONE]="<none>",
	[GLSL_BUILTIN_TYPE_INT]="int",
	[GLSL_BUILTIN_TYPE_VOID]="void",
	[GLSL_BUILTIN_TYPE_BOOL]="bool",
	[GLSL_BUILTIN_TYPE_FLOAT]="float",
	[GLSL_BUILTIN_TYPE_MAT22]="mat2",
	[GLSL_BUILTIN_TYPE_MAT33]="mat3",
	[GLSL_BUILTIN_TYPE_MAT44]="mat4",
	[GLSL_BUILTIN_TYPE_MAT23]="mat2x3",
	[GLSL_BUILTIN_TYPE_MAT24]="mat2x4",
	[GLSL_BUILTIN_TYPE_MAT32]="mat3x2",
	[GLSL_BUILTIN_TYPE_MAT34]="mat3x4",
	[GLSL_BUILTIN_TYPE_MAT42]="mat4x2",
	[GLSL_BUILTIN_TYPE_MAT43]="mat4x3",
	[GLSL_BUILTIN_TYPE_VEC2]="vec2",
	[GLSL_BUILTIN_TYPE_VEC3]="vec3",
	[GLSL_BUILTIN_TYPE_VEC4]="vec4",
	[GLSL_BUILTIN_TYPE_IVEC2]="ivec2",
	[GLSL_BUILTIN_TYPE_IVEC3]="ivec3",
	[GLSL_BUILTIN_TYPE_IVEC4]="ivec4",
	[GLSL_BUILTIN_TYPE_BVEC2]="bvec2",
	[GLSL_BUILTIN_TYPE_BVEC3]="bvec3",
	[GLSL_BUILTIN_TYPE_BVEC4]="bvec4",
	[GLSL_BUILTIN_TYPE_UINT]="uint",
	[GLSL_BUILTIN_TYPE_UVEC2]="uvec2",
	[GLSL_BUILTIN_TYPE_UVEC3]="uvec3",
	[GLSL_BUILTIN_TYPE_UVEC4]="uvec4",
	[GLSL_BUILTIN_TYPE_SAMPLER_1D]="sampler1D",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D]="sampler2D",
	[GLSL_BUILTIN_TYPE_SAMPLER_3D]="sampler3D",
	[GLSL_BUILTIN_TYPE_SAMPLER_CB]="samplerCube",
	[GLSL_BUILTIN_TYPE_SAMPLER_1D_SHADOW]="sampler1DShadow",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_SHADOW]="sampler2DShadow",
	[GLSL_BUILTIN_TYPE_SAMPLER_CB_SHADOW]="samplerCubeShadow",
	[GLSL_BUILTIN_TYPE_SAMPLER_1D_ARRAY]="sampler1DArray",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_ARRAY]="sampler2DArray",
	[GLSL_BUILTIN_TYPE_SAMPLER_1D_ARRAY_SHADOW]="sampler1DArrayShadow",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_ARRAY_SHADOW]="sampler2DArrayShadow",
	[GLSL_BUILTIN_TYPE_ISAMPLER_1D]="isampler1D",
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D]="isampler2D",
	[GLSL_BUILTIN_TYPE_ISAMPLER_3D]="isampler3D",
	[GLSL_BUILTIN_TYPE_ISAMPLER_CB]="isamplerCube",
	[GLSL_BUILTIN_TYPE_ISAMPLER_1D_ARRAY]="isampler1DArray",
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_ARRAY]="isampler2DArray",
	[GLSL_BUILTIN_TYPE_USAMPLER_1D]="usampler1D",
	[GLSL_BUILTIN_TYPE_USAMPLER_2D]="usampler2D",
	[GLSL_BUILTIN_TYPE_USAMPLER_3D]="usampler3D",
	[GLSL_BUILTIN_TYPE_USAMPLER_CB]="usamplerCube",
	[GLSL_BUILTIN_TYPE_USAMPLER_1D_ARRAY]="usampler1DArray",
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_ARRAY]="usampler2DArray",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_RECT]="sampler2DRect",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_RECT_SHADOW]="sampler2DRectShadow",
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_RECT]="isampler2DRect",
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_RECT]="usampler2DRect",
	[GLSL_BUILTIN_TYPE_SAMPLER_BUFFER]="samplerBuffer",
	[GLSL_BUILTIN_TYPE_ISAMPLER_BUFFER]="isamplerBuffer",
	[GLSL_BUILTIN_TYPE_USAMPLER_BUFFER]="usamplerBuffer",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_MULTI_SAMPLE]="sampler2DMS",
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_MULTI_SAMPLE]="isampler2DMS",
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_MULTI_SAMPLE]="usampler2DMS",
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_MULTI_SAMPLE_ARRAY]="sampler2DMSArray",
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_MULTI_SAMPLE_ARRAY]="isampler2DMSArray",
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_MULTI_SAMPLE_ARRAY]="usampler2DMSArray",
};



static const u32 _glsl_builtin_type_to_size[GLSL_BUILTIN_MAX_TYPE+1]={
	[GLSL_BUILTIN_TYPE_INT]=1,
	[GLSL_BUILTIN_TYPE_BOOL]=1,
	[GLSL_BUILTIN_TYPE_FLOAT]=1,
	[GLSL_BUILTIN_TYPE_MAT22]=4,
	[GLSL_BUILTIN_TYPE_MAT33]=9,
	[GLSL_BUILTIN_TYPE_MAT44]=16,
	[GLSL_BUILTIN_TYPE_MAT23]=6,
	[GLSL_BUILTIN_TYPE_MAT24]=8,
	[GLSL_BUILTIN_TYPE_MAT32]=6,
	[GLSL_BUILTIN_TYPE_MAT34]=12,
	[GLSL_BUILTIN_TYPE_MAT42]=8,
	[GLSL_BUILTIN_TYPE_MAT43]=12,
	[GLSL_BUILTIN_TYPE_VEC2]=2,
	[GLSL_BUILTIN_TYPE_VEC3]=3,
	[GLSL_BUILTIN_TYPE_VEC4]=4,
	[GLSL_BUILTIN_TYPE_IVEC2]=2,
	[GLSL_BUILTIN_TYPE_IVEC3]=3,
	[GLSL_BUILTIN_TYPE_IVEC4]=4,
	[GLSL_BUILTIN_TYPE_BVEC2]=2,
	[GLSL_BUILTIN_TYPE_BVEC3]=3,
	[GLSL_BUILTIN_TYPE_BVEC4]=4,
	[GLSL_BUILTIN_TYPE_UINT]=1,
	[GLSL_BUILTIN_TYPE_UVEC2]=2,
	[GLSL_BUILTIN_TYPE_UVEC3]=3,
	[GLSL_BUILTIN_TYPE_UVEC4]=4,
};



static const u32 _glsl_builtin_type_to_slot_count[GLSL_BUILTIN_MAX_TYPE+1]={
	[GLSL_BUILTIN_TYPE_NONE]=0,
	[GLSL_BUILTIN_TYPE_INT]=1,
	[GLSL_BUILTIN_TYPE_VOID]=1,
	[GLSL_BUILTIN_TYPE_BOOL]=1,
	[GLSL_BUILTIN_TYPE_FLOAT]=1,
	[GLSL_BUILTIN_TYPE_MAT22]=2,
	[GLSL_BUILTIN_TYPE_MAT33]=3,
	[GLSL_BUILTIN_TYPE_MAT44]=4,
	[GLSL_BUILTIN_TYPE_MAT23]=2,
	[GLSL_BUILTIN_TYPE_MAT24]=2,
	[GLSL_BUILTIN_TYPE_MAT32]=3,
	[GLSL_BUILTIN_TYPE_MAT34]=3,
	[GLSL_BUILTIN_TYPE_MAT42]=4,
	[GLSL_BUILTIN_TYPE_MAT43]=4,
	[GLSL_BUILTIN_TYPE_VEC2]=1,
	[GLSL_BUILTIN_TYPE_VEC3]=1,
	[GLSL_BUILTIN_TYPE_VEC4]=1,
	[GLSL_BUILTIN_TYPE_IVEC2]=1,
	[GLSL_BUILTIN_TYPE_IVEC3]=1,
	[GLSL_BUILTIN_TYPE_IVEC4]=1,
	[GLSL_BUILTIN_TYPE_BVEC2]=1,
	[GLSL_BUILTIN_TYPE_BVEC3]=1,
	[GLSL_BUILTIN_TYPE_BVEC4]=1,
	[GLSL_BUILTIN_TYPE_UINT]=1,
	[GLSL_BUILTIN_TYPE_UVEC2]=1,
	[GLSL_BUILTIN_TYPE_UVEC3]=1,
	[GLSL_BUILTIN_TYPE_UVEC4]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_1D]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_3D]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_CB]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_1D_SHADOW]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_SHADOW]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_CB_SHADOW]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_1D_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_1D_ARRAY_SHADOW]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_ARRAY_SHADOW]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_1D]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_3D]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_CB]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_1D_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_1D]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_2D]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_3D]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_CB]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_1D_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_RECT]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_RECT_SHADOW]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_RECT]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_RECT]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_BUFFER]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_BUFFER]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_BUFFER]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_MULTI_SAMPLE]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_MULTI_SAMPLE]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_MULTI_SAMPLE]=1,
	[GLSL_BUILTIN_TYPE_SAMPLER_2D_MULTI_SAMPLE_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_ISAMPLER_2D_MULTI_SAMPLE_ARRAY]=1,
	[GLSL_BUILTIN_TYPE_USAMPLER_2D_MULTI_SAMPLE_ARRAY]=1,
};



static const u32 _glsl_builtin_type_to_vector_length[GLSL_BUILTIN_MAX_TYPE+1]={
	[GLSL_BUILTIN_TYPE_FLOAT]=1,
	[GLSL_BUILTIN_TYPE_INT]=1,
	[GLSL_BUILTIN_TYPE_UINT]=1,
	[GLSL_BUILTIN_TYPE_BOOL]=1,
	[GLSL_BUILTIN_TYPE_VEC2]=2,
	[GLSL_BUILTIN_TYPE_IVEC2]=2,
	[GLSL_BUILTIN_TYPE_UVEC2]=2,
	[GLSL_BUILTIN_TYPE_BVEC2]=2,
	[GLSL_BUILTIN_TYPE_VEC3]=3,
	[GLSL_BUILTIN_TYPE_IVEC3]=3,
	[GLSL_BUILTIN_TYPE_UVEC3]=3,
	[GLSL_BUILTIN_TYPE_BVEC3]=3,
	[GLSL_BUILTIN_TYPE_VEC4]=4,
	[GLSL_BUILTIN_TYPE_IVEC4]=4,
	[GLSL_BUILTIN_TYPE_UVEC4]=4,
	[GLSL_BUILTIN_TYPE_BVEC4]=4,
	[GLSL_BUILTIN_TYPE_MAT22]=2,
	[GLSL_BUILTIN_TYPE_MAT33]=3,
	[GLSL_BUILTIN_TYPE_MAT44]=4,
	[GLSL_BUILTIN_TYPE_MAT23]=2,
	[GLSL_BUILTIN_TYPE_MAT24]=2,
	[GLSL_BUILTIN_TYPE_MAT32]=3,
	[GLSL_BUILTIN_TYPE_MAT34]=3,
	[GLSL_BUILTIN_TYPE_MAT42]=4,
	[GLSL_BUILTIN_TYPE_MAT43]=4,
};



static const u32 _glsl_builtin_type_to_vector_count[GLSL_BUILTIN_MAX_TYPE+1]={
	[GLSL_BUILTIN_TYPE_FLOAT]=1,
	[GLSL_BUILTIN_TYPE_INT]=1,
	[GLSL_BUILTIN_TYPE_UINT]=1,
	[GLSL_BUILTIN_TYPE_BOOL]=1,
	[GLSL_BUILTIN_TYPE_VEC2]=1,
	[GLSL_BUILTIN_TYPE_IVEC2]=1,
	[GLSL_BUILTIN_TYPE_UVEC2]=1,
	[GLSL_BUILTIN_TYPE_BVEC2]=1,
	[GLSL_BUILTIN_TYPE_VEC3]=1,
	[GLSL_BUILTIN_TYPE_IVEC3]=1,
	[GLSL_BUILTIN_TYPE_UVEC3]=1,
	[GLSL_BUILTIN_TYPE_BVEC3]=1,
	[GLSL_BUILTIN_TYPE_VEC4]=1,
	[GLSL_BUILTIN_TYPE_IVEC4]=1,
	[GLSL_BUILTIN_TYPE_UVEC4]=1,
	[GLSL_BUILTIN_TYPE_BVEC4]=1,
	[GLSL_BUILTIN_TYPE_MAT22]=2,
	[GLSL_BUILTIN_TYPE_MAT33]=3,
	[GLSL_BUILTIN_TYPE_MAT44]=4,
	[GLSL_BUILTIN_TYPE_MAT23]=3,
	[GLSL_BUILTIN_TYPE_MAT24]=4,
	[GLSL_BUILTIN_TYPE_MAT32]=2,
	[GLSL_BUILTIN_TYPE_MAT34]=4,
	[GLSL_BUILTIN_TYPE_MAT42]=2,
	[GLSL_BUILTIN_TYPE_MAT43]=3,
};



static const glsl_builtin_type_t _glsl_builtin_type_vector_to_base_type[]={
	[GLSL_BUILTIN_TYPE_FLOAT]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_INT]=GLSL_BUILTIN_TYPE_INT,
	[GLSL_BUILTIN_TYPE_UINT]=GLSL_BUILTIN_TYPE_UINT,
	[GLSL_BUILTIN_TYPE_BOOL]=GLSL_BUILTIN_TYPE_BOOL,
	[GLSL_BUILTIN_TYPE_VEC2]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_IVEC2]=GLSL_BUILTIN_TYPE_INT,
	[GLSL_BUILTIN_TYPE_UVEC2]=GLSL_BUILTIN_TYPE_UINT,
	[GLSL_BUILTIN_TYPE_BVEC2]=GLSL_BUILTIN_TYPE_BOOL,
	[GLSL_BUILTIN_TYPE_VEC3]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_IVEC3]=GLSL_BUILTIN_TYPE_INT,
	[GLSL_BUILTIN_TYPE_UVEC3]=GLSL_BUILTIN_TYPE_UINT,
	[GLSL_BUILTIN_TYPE_BVEC3]=GLSL_BUILTIN_TYPE_BOOL,
	[GLSL_BUILTIN_TYPE_VEC4]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_IVEC4]=GLSL_BUILTIN_TYPE_INT,
	[GLSL_BUILTIN_TYPE_UVEC4]=GLSL_BUILTIN_TYPE_UINT,
	[GLSL_BUILTIN_TYPE_BVEC4]=GLSL_BUILTIN_TYPE_BOOL,
	[GLSL_BUILTIN_TYPE_MAT22]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT33]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT44]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT23]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT24]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT32]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT34]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT42]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_MAT43]=GLSL_BUILTIN_TYPE_FLOAT,
};



static const glsl_builtin_type_t _glsl_builtin_type_vector_from_base_type_and_length[][4]={
	[GLSL_BUILTIN_TYPE_FLOAT][0]=GLSL_BUILTIN_TYPE_FLOAT,
	[GLSL_BUILTIN_TYPE_FLOAT][1]=GLSL_BUILTIN_TYPE_VEC2,
	[GLSL_BUILTIN_TYPE_FLOAT][2]=GLSL_BUILTIN_TYPE_VEC3,
	[GLSL_BUILTIN_TYPE_FLOAT][3]=GLSL_BUILTIN_TYPE_VEC4,
	[GLSL_BUILTIN_TYPE_INT][0]=GLSL_BUILTIN_TYPE_INT,
	[GLSL_BUILTIN_TYPE_INT][1]=GLSL_BUILTIN_TYPE_IVEC2,
	[GLSL_BUILTIN_TYPE_INT][2]=GLSL_BUILTIN_TYPE_IVEC3,
	[GLSL_BUILTIN_TYPE_INT][3]=GLSL_BUILTIN_TYPE_IVEC4,
	[GLSL_BUILTIN_TYPE_UINT][0]=GLSL_BUILTIN_TYPE_UINT,
	[GLSL_BUILTIN_TYPE_UINT][1]=GLSL_BUILTIN_TYPE_UVEC2,
	[GLSL_BUILTIN_TYPE_UINT][2]=GLSL_BUILTIN_TYPE_UVEC3,
	[GLSL_BUILTIN_TYPE_UINT][3]=GLSL_BUILTIN_TYPE_UVEC4,
	[GLSL_BUILTIN_TYPE_BOOL][0]=GLSL_BUILTIN_TYPE_BOOL,
	[GLSL_BUILTIN_TYPE_BOOL][1]=GLSL_BUILTIN_TYPE_BVEC2,
	[GLSL_BUILTIN_TYPE_BOOL][2]=GLSL_BUILTIN_TYPE_BVEC3,
	[GLSL_BUILTIN_TYPE_BOOL][3]=GLSL_BUILTIN_TYPE_BVEC4
};



SYS_PUBLIC _Bool glsl_builtin_type_is_compatible(glsl_builtin_type_t src,glsl_builtin_type_t dst){
	if (src==dst){
		return 1;
	}
	if (dst==GLSL_BUILTIN_TYPE_FLOAT){
		return src==GLSL_BUILTIN_TYPE_INT||src==GLSL_BUILTIN_TYPE_UINT;
	}
	if (dst==GLSL_BUILTIN_TYPE_VEC2){
		return src==GLSL_BUILTIN_TYPE_IVEC2||src==GLSL_BUILTIN_TYPE_UVEC2;
	}
	if (dst==GLSL_BUILTIN_TYPE_VEC3){
		return src==GLSL_BUILTIN_TYPE_IVEC3||src==GLSL_BUILTIN_TYPE_UVEC3;
	}
	if (dst==GLSL_BUILTIN_TYPE_VEC4){
		return src==GLSL_BUILTIN_TYPE_IVEC4||src==GLSL_BUILTIN_TYPE_UVEC4;
	}
	return 0;
}



SYS_PUBLIC const char* glsl_builtin_type_to_string(glsl_builtin_type_t builtin_type){
	return _glsl_builtin_type_to_string[builtin_type];
}



SYS_PUBLIC u32 glsl_builtin_type_to_size(glsl_builtin_type_t builtin_type){
	return _glsl_builtin_type_to_size[builtin_type];
}



SYS_PUBLIC u32 glsl_builtin_type_to_slot_count(glsl_builtin_type_t builtin_type){
	return _glsl_builtin_type_to_slot_count[builtin_type];
}



SYS_PUBLIC u32 glsl_builtin_type_to_vector_length(glsl_builtin_type_t builtin_type){
	return _glsl_builtin_type_to_vector_length[builtin_type];
}



SYS_PUBLIC u32 glsl_builtin_type_to_vector_count(glsl_builtin_type_t builtin_type){
	return _glsl_builtin_type_to_vector_count[builtin_type];
}



SYS_PUBLIC u32 glsl_builtin_type_to_vector_base_type(glsl_builtin_type_t builtin_type){
	return _glsl_builtin_type_vector_to_base_type[builtin_type];
}



SYS_PUBLIC u32 glsl_builtin_type_from_base_type_and_length(glsl_builtin_type_t builtin_type,u32 length){
	return _glsl_builtin_type_vector_from_base_type_and_length[builtin_type][length-1];
}
