#ifndef _VIRTIO_GPU_REGISTERS_H_
#define _VIRTIO_GPU_REGISTERS_H_ 1
#include <kernel/types.h>



#define VIRTIO_GPU_MAX_SCANOUTS 16



// Features
#define VIRTIO_GPU_F_VIRGL 0
#define VIRTIO_GPU_F_EDID 1

// Registers
#define VIRTIO_GPU_REG_EVENTS_READ 0x00
#define VIRTIO_GPU_REG_EVENTS_CLEAR 0x04
#define VIRTIO_GPU_REG_NUM_SCANOUTS 0x08
#define VIRTIO_GPU_REG_NUM_CAPSETS 0x0c

// Events
#define VIRTIO_GPU_EVENT_DISPLAY 0x01

// Commands
#define VIRTIO_GPU_CMD_GET_DISPLAY_INFO 0x0100
#define VIRTIO_GPU_CMD_RESOURCE_CREATE_2D 0x0101
#define VIRTIO_GPU_CMD_RESOURCE_UNREF 0x0102
#define VIRTIO_GPU_CMD_SET_SCANOUT 0x0103
#define VIRTIO_GPU_CMD_RESOURCE_FLUSH 0x0104
#define VIRTIO_GPU_CMD_TRANSFER_TO_HOST_2D 0x0105
#define VIRTIO_GPU_CMD_RESOURCE_ATTACH_BACKING 0x0106
#define VIRTIO_GPU_CMD_RESOURCE_DETACH_BACKING 0x0107
#define VIRTIO_GPU_CMD_GET_CAPSET_INFO 0x0108
#define VIRTIO_GPU_CMD_GET_CAPSET 0x0109
#define VIRTIO_GPU_CMD_GET_EDID 0x010a
#define VIRTIO_GPU_CMD_RESOURCE_ASSIGN_UUID 0x010b
#define VIRTIO_GPU_CMD_RESOURCE_CREATE_BLOB 0x010c
#define VIRTIO_GPU_CMD_SET_SCANOUT_BLOB 0x010d
#define VIRTIO_GPU_CMD_CTX_CREATE 0x0200e
#define VIRTIO_GPU_CMD_CTX_DESTROY 0x0201
#define VIRTIO_GPU_CMD_CTX_ATTACH_RESOURCE 0x0202
#define VIRTIO_GPU_CMD_CTX_DETACH_RESOURCE 0x0203
#define VIRTIO_GPU_CMD_RESOURCE_CREATE_3D 0x0204
#define VIRTIO_GPU_CMD_TRANSFER_TO_HOST_3D 0x0205
#define VIRTIO_GPU_CMD_TRANSFER_FROM_HOST_3D 0x0206
#define VIRTIO_GPU_CMD_SUBMIT_3D 0x0207
#define VIRTIO_GPU_CMD_RESOURCE_MAP_BLOB 0x0208
#define VIRTIO_GPU_CMD_RESOURCE_UNMAP_BLOB 0x0209
#define VIRTIO_GPU_CMD_UPDATE_CURSOR 0x0300
#define VIRTIO_GPU_CMD_MOVE_CURSOR 0x0301
#define VIRTIO_GPU_RESP_OK_NODATA 0x1100
#define VIRTIO_GPU_RESP_OK_DISPLAY_INFO 0x1101
#define VIRTIO_GPU_RESP_OK_CAPSET_INFO 0x1102
#define VIRTIO_GPU_RESP_OK_CAPSET 0x1103
#define VIRTIO_GPU_RESP_OK_EDID 0x1104
#define VIRTIO_GPU_RESP_OK_RESOURCE_UUID 0x1105
#define VIRTIO_GPU_RESP_OK_MAP_INFO 0x1106
#define VIRTIO_GPU_RESP_ERR_UNSPEC 0x1200
#define VIRTIO_GPU_RESP_ERR_OUT_OF_MEMORY 0x1201
#define VIRTIO_GPU_RESP_ERR_INVALID_SCANOUT_ID 0x1202
#define VIRTIO_GPU_RESP_ERR_INVALID_RESOURCE_ID 0x1203
#define VIRTIO_GPU_RESP_ERR_INVALID_CONTEXT_ID 0x1204
#define VIRTIO_GPU_RESP_ERR_INVALID_PARAMETER 0x1205

// Flags
#define VIRTIO_GPU_FLAG_FENCE 0x01
#define VIRTIO_GPU_FLAG_INFO_RING_IDX 0x02



typedef struct KERNEL_PACKED _VIRTIO_GPU_CONTROL_HEADER{
	u32 type;
	u32 flags;
	u64 fence_id;
	u32 ctx_id;
	u8 ring_idx;
	u8 _padding[3];
} virtio_gpu_control_header_t;



typedef struct KERNEL_PACKED _VIRTIO_GPU_RECT{
	u32 x;
	u32 y;
	u32 width;
	u32 height;
} virtio_gpu_rect_t;



typedef struct KERNEL_PACKED _VIRTIO_GPU_RESP_DISPLAY_INFO{
	virtio_gpu_control_header_t header;
	struct KERNEL_PACKED{
		virtio_gpu_rect_t rect;
		u32 enabled;
		u32 flags;
	} displays[VIRTIO_GPU_MAX_SCANOUTS];
} virtio_gpu_resp_display_info_t;



typedef struct KERNEL_PACKED _VIRTIO_GPU_GET_EDID{
	virtio_gpu_control_header_t header;
	u32 scanout;
	u32 _padding;
} virtio_gpu_get_edid_t;



typedef struct KERNEL_PACKED _VIRTIO_GPU_RESP_EDID{
	virtio_gpu_control_header_t header;
	u32 size;
	u32 _padding;
	u8 edid[1024];
} virtio_gpu_resp_edid_t;



#endif
