#include <kernel/log/log.h>
#include <kernel/memory/pmm.h>
#include <kernel/memory/vmm.h>
#include <kernel/kernel.h>
#include <kernel/types.h>
#define KERNEL_LOG_NAME "aml"



#define OP_ZERO 0x00
#define OP_ONE 0x01
#define OP_ALIAS 0x06
#define OP_NAME 0x08
#define OP_BYTE_PREFIX 0x0a
#define OP_WORD_PREFIX 0x0b
#define OP_DWORD_PREFIX 0x0c
#define OP_STRING_PREFIX 0x0d
#define OP_QWORD_PREFIX 0x0e
#define OP_SCOPE 0x10
#define OP_BUFFER 0x11
#define OP_PACKAGE 0x12
#define OP_VAR_PACKAGE 0x13
#define OP_METHOD 0x14
#define OP_LOCAL0 0x60
#define OP_LOCAL1 0x61
#define OP_LOCAL2 0x62
#define OP_LOCAL3 0x63
#define OP_LOCAL4 0x64
#define OP_LOCAL5 0x65
#define OP_LOCAL6 0x66
#define OP_LOCAL7 0x67
#define OP_ARG0 0x68
#define OP_ARG1 0x69
#define OP_ARG2 0x6a
#define OP_ARG3 0x6b
#define OP_ARG4 0x6c
#define OP_ARG5 0x6d
#define OP_ARG6 0x6e
#define OP_STORE 0x70
#define OP_REF_OF 0x71
#define OP_ADD 0x72
#define OP_CONCAT 0x73
#define OP_SUBTRACT 0x74
#define OP_INCREMENT 0x75
#define OP_DECREMENT 0x76
#define OP_MULTIPLY 0x77
#define OP_DIVIDE 0x78
#define OP_SHIFT_LEFT 0x79
#define OP_SHIFT_RIGHT 0x7a
#define OP_AND 0x7b
#define OP_NAND 0x7c
#define OP_OR 0x7d
#define OP_NOR 0x7e
#define OP_XOR 0x7f
#define OP_NOT 0x80
#define OP_FIND_SET_LEFT_BIT 0x81
#define OP_FIND_SET_RIGHT_BIT 0x82
#define OP_DEREF_OF 0x83
#define OP_CONCAT_RES 0x84
#define OP_MOD 0x85
#define OP_NOTIFY 0x86
#define OP_SIZE_OF 0x87
#define OP_INDEX 0x88
#define OP_MATCH 0x89
#define OP_CREATE_D_WORD_FIELD 0x8a
#define OP_CREATE_WORD_FIELD 0x8b
#define OP_CREATE_BYTE_FIELD 0x8c
#define OP_CREATE_BIT_FIELD 0x8d
#define OP_OBJECT_TYPE 0x8e
#define OP_CREATE_Q_WORD_FIELD 0x8f
#define OP_L_AND 0x90
#define OP_L_OR 0x91
#define OP_L_NOT 0x92
#define OP_L_EQUAL 0x93
#define OP_L_GREATER 0x94
#define OP_L_LESS 0x95
#define OP_TO_BUFFER 0x96
#define OP_TO_DECIMAL_STRING 0x97
#define OP_TO_HEX_STRING 0x98
#define OP_TO_INTEGER 0x99
#define OP_TO_STRING 0x9c
#define OP_COPY_OBJECT 0x9d
#define OP_MID 0x9e
#define OP_CONTINUE 0x9f
#define OP_IF 0xa0
#define OP_ELSE 0xa1
#define OP_WHILE 0xa2
#define OP_NOOP 0xa3
#define OP_RETURN 0xa4
#define OP_BREAK 0xa5
#define OP_BREAK_POINT 0xcc
#define OP_ONES 0xff

#define OP_EXT_MUTEX 0x01
#define OP_EXT_EVENT 0x02
#define OP_EXT_COND_REF_OF 0x12
#define OP_EXT_CREATE_FIELD 0x13
#define OP_EXT_LOAD_TABLE 0x1f
#define OP_EXT_LOAD 0x20
#define OP_EXT_STALL 0x21
#define OP_EXT_SLEEP 0x22
#define OP_EXT_ACQUIRE 0x23
#define OP_EXT_SIGNAL 0x24
#define OP_EXT_WAIT 0x25
#define OP_EXT_RESET 0x26
#define OP_EXT_RELEASE 0x27
#define OP_EXT_FROM_BCD 0x28
#define OP_EXT_TO_BCD 0x29
#define OP_EXT_UNLOAD 0x2a
#define OP_EXT_REVISION 0x30
#define OP_EXT_DEBUG 0x31
#define OP_EXT_FATAL 0x32
#define OP_EXT_TIMER 0x33
#define OP_EXT_REGION 0x80
#define OP_EXT_FIELD 0x81
#define OP_EXT_DEVICE 0x82
#define OP_EXT_PROCESSOR 0x83
#define OP_EXT_POWER_RES 0x84
#define OP_EXT_THERMAL_ZONE 0x85
#define OP_EXT_INDEX_FIELD 0x86
#define OP_EXT_BANK_FIELD 0x87
#define OP_EXT_DATA_REGION 0x88

#define OPCODE_FLAG_EXTENDED 0x01
#define OPCODE_FLAG_PKGLENGTH 0x02

#define OPCODE_ARG_UINT8 1
#define OPCODE_ARG_UINT16 2
#define OPCODE_ARG_UINT32 3
#define OPCODE_ARG_UINT64 4
#define OPCODE_ARG_STRING 5
#define OPCODE_ARG_NAME 6
#define OPCODE_ARG_OBJECT 7



#define _DECL_OPCODE_ARG_COUNT(_,_0,_1,_2,_3,_4,_5,n,...) n
#define DECL_OPCODE(opcode,flags,...) {opcode,flags,_DECL_OPCODE_ARG_COUNT(_,##__VA_ARGS__,6,5,4,3,2,1,0),{__VA_ARGS__}}



typedef struct _AML_OPCODE{
	u16 opcode;
	u8 flags;
	u8 arg_count;
	u8 args[6];
} aml_opcode_t;



static const aml_opcode_t _aml_opcodes[]={
	DECL_OPCODE(OP_ZERO,0),
	DECL_OPCODE(OP_ONE,0),
	DECL_OPCODE(OP_ALIAS,0,OPCODE_ARG_NAME,OPCODE_ARG_NAME),
	DECL_OPCODE(OP_NAME,0,OPCODE_ARG_NAME,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_BYTE_PREFIX,0,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_WORD_PREFIX,0,OPCODE_ARG_UINT16),
	DECL_OPCODE(OP_DWORD_PREFIX,0,OPCODE_ARG_UINT32),
	DECL_OPCODE(OP_STRING_PREFIX,0,OPCODE_ARG_STRING),
	DECL_OPCODE(OP_QWORD_PREFIX,0,OPCODE_ARG_UINT64),
	DECL_OPCODE(OP_SCOPE,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME),
	DECL_OPCODE(OP_BUFFER,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_PACKAGE,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_VAR_PACKAGE,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_METHOD,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_LOCAL0,0),
	DECL_OPCODE(OP_LOCAL1,0),
	DECL_OPCODE(OP_LOCAL2,0),
	DECL_OPCODE(OP_LOCAL3,0),
	DECL_OPCODE(OP_LOCAL4,0),
	DECL_OPCODE(OP_LOCAL5,0),
	DECL_OPCODE(OP_LOCAL6,0),
	DECL_OPCODE(OP_LOCAL7,0),
	DECL_OPCODE(OP_ARG0,0),
	DECL_OPCODE(OP_ARG1,0),
	DECL_OPCODE(OP_ARG2,0),
	DECL_OPCODE(OP_ARG3,0),
	DECL_OPCODE(OP_ARG4,0),
	DECL_OPCODE(OP_ARG5,0),
	DECL_OPCODE(OP_ARG6,0),
	DECL_OPCODE(OP_STORE,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_REF_OF,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_ADD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_CONCAT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_SUBTRACT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_INCREMENT,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_DECREMENT,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_MULTIPLY,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_DIVIDE,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_SHIFT_LEFT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_SHIFT_RIGHT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_AND,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_NAND,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_OR,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_NOR,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_XOR,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_NOT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_FIND_SET_LEFT_BIT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_FIND_SET_RIGHT_BIT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_DEREF_OF,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_CONCAT_RES,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_MOD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_NOTIFY,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_SIZE_OF,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_INDEX,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_MATCH,0,OPCODE_ARG_OBJECT,OPCODE_ARG_UINT8,OPCODE_ARG_OBJECT,OPCODE_ARG_UINT8,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_CREATE_D_WORD_FIELD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_NAME,  ),
	DECL_OPCODE(OP_CREATE_WORD_FIELD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_NAME,  ),
	DECL_OPCODE(OP_CREATE_BYTE_FIELD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_NAME,  ),
	DECL_OPCODE(OP_CREATE_BIT_FIELD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_NAME,  ),
	DECL_OPCODE(OP_OBJECT_TYPE,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_CREATE_Q_WORD_FIELD,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_NAME,  ),
	DECL_OPCODE(OP_L_AND,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_L_OR,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_L_NOT,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_L_EQUAL,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_L_GREATER,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_L_LESS,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_TO_BUFFER,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_TO_DECIMAL_STRING,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_TO_HEX_STRING,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_TO_INTEGER,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_TO_STRING,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_COPY_OBJECT,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_MID,0,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_CONTINUE,0),
	DECL_OPCODE(OP_IF,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_ELSE,OPCODE_FLAG_PKGLENGTH),
	DECL_OPCODE(OP_WHILE,OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_NOOP,0),
	DECL_OPCODE(OP_RETURN,0,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_BREAK,0),
	DECL_OPCODE(OP_BREAK_POINT,0),
	DECL_OPCODE(OP_ONES,0),
	DECL_OPCODE(OP_EXT_MUTEX,OPCODE_FLAG_EXTENDED,OPCODE_ARG_NAME,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_EXT_EVENT,OPCODE_FLAG_EXTENDED,OPCODE_ARG_NAME),
	DECL_OPCODE(OP_EXT_COND_REF_OF,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_CREATE_FIELD,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_NAME),
	DECL_OPCODE(OP_EXT_LOAD_TABLE,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_LOAD,OPCODE_FLAG_EXTENDED,OPCODE_ARG_NAME,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_STALL,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_SLEEP,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_ACQUIRE,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_UINT16),
	DECL_OPCODE(OP_EXT_SIGNAL,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_WAIT,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_RESET,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_RELEASE,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_FROM_BCD,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_TO_BCD,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_UNLOAD,OPCODE_FLAG_EXTENDED,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_REVISION,OPCODE_FLAG_EXTENDED),
	DECL_OPCODE(OP_EXT_DEBUG,OPCODE_FLAG_EXTENDED),
	DECL_OPCODE(OP_EXT_FATAL,OPCODE_FLAG_EXTENDED,OPCODE_ARG_UINT8,OPCODE_ARG_UINT32,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_TIMER,OPCODE_FLAG_EXTENDED),
	DECL_OPCODE(OP_EXT_REGION,OPCODE_FLAG_EXTENDED,OPCODE_ARG_NAME,OPCODE_ARG_UINT8,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	DECL_OPCODE(OP_EXT_FIELD,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_EXT_DEVICE,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME),
	DECL_OPCODE(OP_EXT_PROCESSOR,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME,OPCODE_ARG_UINT8,OPCODE_ARG_UINT32,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_EXT_POWER_RES,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME,OPCODE_ARG_UINT8,OPCODE_ARG_UINT16),
	DECL_OPCODE(OP_EXT_THERMAL_ZONE,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME),
	DECL_OPCODE(OP_EXT_INDEX_FIELD,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME,OPCODE_ARG_NAME,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_EXT_BANK_FIELD,OPCODE_FLAG_EXTENDED|OPCODE_FLAG_PKGLENGTH,OPCODE_ARG_NAME,OPCODE_ARG_NAME,OPCODE_ARG_OBJECT,OPCODE_ARG_UINT8),
	DECL_OPCODE(OP_EXT_DATA_REGION,OPCODE_FLAG_EXTENDED,OPCODE_ARG_NAME,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT,OPCODE_ARG_OBJECT),
	{0xff,0xff}
};



typedef struct _OBJECT{
	u8 opcode;
	u32 arg_count;
} object_t;



typedef struct _ALLOCATOR{
	u64 top;
	u64 max_top;
} allocator_t;



// static void* _allocate_data(allocator_t* allocator,u32 size){
// 	size=(size+7)&0xfffffffffffffff8ull;
// 	while (allocator->top+size>allocator->max_top){
// 		vmm_map_page(&vmm_kernel_pagemap,pmm_alloc(1,PMM_COUNTER_CPU),allocator->max_top,VMM_PAGE_FLAG_PRESENT|VMM_PAGE_FLAG_READWRITE|VMM_PAGE_FLAG_USER);
// 		allocator->max_top+=PAGE_SIZE;
// 	}
// 	void* out=(void*)(allocator->top);
// 	allocator->top+=size;
// 	return out;
// }



// static void* _allocate_object(allocator_t* allocator,u8 type,u32 size,u32 array_size){
// 	object_header_t* out=_allocate_data(allocator,size);
// 	out->type=type;
// 	if (array_size!=OBJECT_NO_ARRAY_SIZE){
// 		object_array_header_t* array=(object_array_header_t*)out;
// 		array->length=array_size;
// 		array->data=_allocate_data(allocator,array_size*sizeof(object_header_t*));
// 	}
// 	return out;
// }



typedef struct _AML_PARSER_STATE{
	const u8* data;
	const u32 length;
	u32 offset;
} aml_parser_state_t;



static u32 _get_name_length(const u8* data){
	u32 out=0;
	if (data[out]=='\\'){
		out++;
	}
	while (data[out]=='^'){
		out++;
	}
	u8 segment_count=1;
	if (data[out]=='.'){
		out++;
		segment_count=2;
	}
	else if (data[out]=='/'){
		out++;
		segment_count=data[out];
		out++;
	}
	else if (!data[out]){
		out++;
		segment_count=0;
	}
	return out+(segment_count<<2);
}



static const aml_opcode_t* _parse_opcode(const u8* data){
	u8 extended=0;
	u8 type=data[0];
	if (type==0x5b){
		extended=OPCODE_FLAG_EXTENDED;
		type=data[1];
	}
	for (const aml_opcode_t* out=_aml_opcodes;out->flags!=0xff;out++){
		if ((out->flags&OPCODE_FLAG_EXTENDED)==extended&&out->opcode==type){
			return out;
		}
	}
	ERROR("Unknown opcode '%s%x'",(extended?"5b ":""),type);
	WARN("%x %x %x %x",data[0],data[1],data[2],data[3]);
	for (;;);
}



static u32 _get_opcode_size(const u8* data,const aml_opcode_t* opcode){
	u32 out=((opcode->flags&OPCODE_FLAG_EXTENDED)?2:1);
	u32 pkglength=0;
	if (opcode->flags&OPCODE_FLAG_PKGLENGTH){
		pkglength=data[out]&0x3f;
		for (u8 i=0;i<(data[out]>>6);i++){
			pkglength|=data[out+i+1]<<(4+8*i);
		}
		return out+pkglength;
		out+=(data[out]>>6)+1;
	}
	for (u8 i=0;i<opcode->arg_count;i++){
		if (opcode->args[i]==OPCODE_ARG_UINT8){
			out++;
		}
		else if (opcode->args[i]==OPCODE_ARG_UINT16){
			out+=2;
		}
		else if (opcode->args[i]==OPCODE_ARG_UINT32){
			out+=4;
		}
		else if (opcode->args[i]==OPCODE_ARG_UINT64){
			out+=8;
		}
		else if (opcode->args[i]==OPCODE_ARG_STRING){
			do{
				out++;
			} while (data[out-1]);
		}
		else if (opcode->args[i]==OPCODE_ARG_NAME){
			out+=_get_name_length(data+out);
		}
		else if (opcode->args[i]==OPCODE_ARG_OBJECT){
			out+=_get_opcode_size(data+out,_parse_opcode(data+out));
			ERROR("OPCODE_ARG_OBJECT");
		}
	}
	return out+pkglength;
}



static void _parse_generic_object(aml_parser_state_t* parser_state,allocator_t* allocator){
	const aml_opcode_t* opcode=_parse_opcode(parser_state->data+parser_state->offset);
	parser_state->offset+=_get_opcode_size(parser_state->data+parser_state->offset,opcode);
	WARN("~ %x",opcode->opcode);
}



void aml_load(const u8* data,u32 length){
	LOG("Loading AML...");
	allocator_t allocator={
		pmm_align_up_address(kernel_get_bss_end()+kernel_get_offset()),
		pmm_align_up_address(kernel_get_bss_end()+kernel_get_offset())
	};
	aml_parser_state_t parser_state={
		data,
		length,
		0
	};
	while (parser_state.offset<parser_state.length){
		_parse_generic_object(&parser_state,&allocator);
	}
}
