name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
permissions: read-all
jobs:
  coverage-test:
    name: Test & Report coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Load cached GCC package
        id: cache-gcc-package
        uses: actions/cache@v3
        with:
          path: gcc-latest.deb
          key: gcc-package
      - name: Download GCC package
        if: steps.cache-gcc-package.outputs.cache-hit != 'true'
        run: wget -q https://kayari.org/gcc-latest/gcc-latest.deb
      - name: Save cached GCC package
        if: steps.cache-gcc-package.outputs.cache-hit != 'true'
        uses: actions/cache/save@v3
        with:
          path: gcc-latest.deb
          key: gcc-package
      - name: Setup environment
        run: |
          sudo dpkg -i gcc-latest.deb
          sudo apt install -y nasm qemu qemu-utils qemu-system-x86 lcov genisoimage
      - name: Build
        run: |
          export PATH=/opt/gcc-latest/bin:$PATH
          export LD_RUN_PATH=/opt/gcc-latest/lib64
          ./build.sh --coverage
      - name: Delete previous coverage
        run: rm -f build/objects/*.gcda
      - name: Execute tests
        run: ./build.sh --coverage --run
      - name: Generate coverage report
        run:
      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        with:lcov -c -d build/objects -o build/coverage.info
          github-token: ${{secrets.GITHUB_TOKEN}}
          file: build/coverage.info
