name: Coverage
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
concurrency:
  group: ${{github.workflow}}-${{github.event.pull_request.number||github.ref}}
  cancel-in-progress: true
permissions: read-all
jobs:
  coverage-test:
    name: Test & Report coverage
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup environment
        run: |
          sudo apt update&&sudo apt install -y nasm gcc-12 qemu qemu-utils qemu-system-x86 gnu-efi ovmf swtpm
          mkdir -p build/external
          curl -L -o /tmp/virtiofsd.zip https://gitlab.com/virtio-fs/virtiofsd/-/jobs/artifacts/main/download?job=publish
          unzip /tmp/virtiofsd.zip -d /tmp/virtiofsd
          cp /tmp/virtiofsd/target/x86_64-unknown-linux-musl/release/virtiofsd build/external/virtiofsd
      - name: Build & Test
        run: |
          echo "nameserver 1.1.1.1" | sudo tee /etc/resolv.conf
          export PYTHONUNBUFFERED=1
          ./build.sh --coverage --run
      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          file: build/coverage.lcov
          format: lcov
